version: '3'

services: 
  app: 
    build: .
    container_name: 'ts-template_app'
    entrypoint: dockerize -wait tcp://db:5432 -timeout 45s ./.docker/entrypoint.sh
    command: "yarn start:dev"
    ports: 
      - 3333:3333
    volumes: 
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    depends_on: 
      - db

  db: 
    build: ./.docker/postgres
    container_name: 'ts-template_db'
    ports: 
      - 5432:5432
    tty: true
    volumes: 
      - ./.docker/pgdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=ts-template
      - POSTGRES_USER=ts-template
      - POSTGRES_PASSWORD=password
